name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get Meteor
      run: curl https://install.meteor.com/ | sh
    - name: Download npm packages
      run:  meteor npm update
    - name: Download meteor packages
      run:  meteor update
    - name: Build project
      run:  meteor build .
    - name: Static analysis of project
      run:  meteor lint
